### ISSUE TITLE
Delete Comments Endpoint passes Username in the place of Workspace

### ISSUE THREAD

**Issue by AlteaDown** [tomasbjerre/violation-comments-to-bitbucket-cloud-lib#1]
It looks like the endpoint being hit by the DeleteComments call is not hitting the workspace (404 is returned). Looking at the BitBucket Cloud v2 api, the delete comment endpoint is here: https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/comments/%7Bcomment_id%7D#delete

In that it says the endpoint is `/2.0/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}`

However, in this project's code it is declared (as used) as the following:
```
@DELETE
@Path("/{username}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}")
```

Note that username is being passed in the place of the workspace.

**Comment by tomasbjerre** [comment]
I started out with the `swagger.json` from: https://api.bitbucket.org/swagger.json

I interpret it as if it is mixing `workspace` and `username`. I choose to use the name `username` everywhere.

What is the full URL giving you 404?
How would you change it?
What would be the value of `workspace` if not same as `username`?

**Comment by tomasbjerre** [comment]
You are probably right about this! I'm changing it now.

**Comment by tomasbjerre** [comment]
This is now changed and released! Open issue again if not working.
