### ISSUE TITLE
Single file comments added to wrong lines

### ISSUE THREAD

**Issue by michal-luszczuk** [tomasbjerre/violation-comments-to-bitbucket-cloud-lib#4]
While using option ` -create-single-file-comments` set to  `true` comments are not referencing valid lines which are returned by violations.

There is no need to translate violation line into diff line.
To post new Comment using Bitbucket API line of file (not of the diff) should be used

Bitbucket Documentation [link](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/comments#post) (: 
![image](https://user-images.githubusercontent.com/9006071/74608757-30d12580-50e4-11ea-98f3-bc19e50b48c8.png)

**Comment by tomasbjerre** [comment]
Will you provide a PR?

**Comment by michal-luszczuk** [comment]
Yes, just did that!

Could you please release new version with those two bugs [1](https://github.com/tomasbjerre/violation-comments-to-bitbucket-cloud-lib/issues/2) [2](https://github.com/tomasbjerre/violation-comments-to-bitbucket-cloud-lib/issues/4)  fixed?

**Comment by tomasbjerre** [comment]
Yes, both are now released!
